
var playerStats = [
    {
      "id": 1,
      "name": "Martin",
      "position": "Defence",
      "appearances": 18,
      "goals": 0,
      "assists": 1,
      "goalInvolvements": 1,
      "motmVotes": 7,
      "motmWins": 1,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 2,
      "name": "Elliott",
      "position": "Defence",
      "appearances": 2,
      "goals": 0,
      "assists": 0,
      "goalInvolvements": 0,
      "motmVotes": 0,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 3,
      "name": "Mike B",
      "position": "Midfield",
      "appearances": 12,
      "goals": 2,
      "assists": 1,
      "goalInvolvements": 3,
      "motmVotes": 16,
      "motmWins": 2,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 4,
      "name": "Tom B",
      "position": "Midfield",
      "appearances": 7,
      "goals": 1,
      "assists": 1,
      "goalInvolvements": 2,
      "motmVotes": 20,
      "motmWins": 1,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 5,
      "name": "Rory",
      "position": "Midfield",
      "appearances": 0,
      "goals": 0,
      "assists": 0,
      "goalInvolvements": 0,
      "motmVotes": 0,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 6,
      "name": "Andy B",
      "position": "Midfield",
      "appearances": 19,
      "goals": 2,
      "assists": 3,
      "goalInvolvements": 5,
      "motmVotes": 35,
      "motmWins": 4,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 7,
      "name": "Jake",
      "position": "Midfield",
      "appearances": 10,
      "goals": 1,
      "assists": 2,
      "goalInvolvements": 3,
      "motmVotes": 1,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 8,
      "name": "James C",
      "position": "Midfield",
      "appearances": 15,
      "goals": 1,
      "assists": 3,
      "goalInvolvements": 4,
      "motmVotes": 3,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 1,
      "stabWounds": 0
    },
    {
      "id": 9,
      "name": "Ben C",
      "position": "Defence",
      "appearances": 6,
      "goals": 1,
      "assists": 0,
      "goalInvolvements": 1,
      "motmVotes": 9,
      "motmWins": 1,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 10,
      "name": "Seb",
      "position": "Striker",
      "appearances": 17,
      "goals": 19,
      "assists": 9,
      "goalInvolvements": 28,
      "motmVotes": 27,
      "motmWins": 3,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 11,
      "name": "Graham",
      "position": "Midfield",
      "appearances": 2,
      "goals": 1,
      "assists": 0,
      "goalInvolvements": 1,
      "motmVotes": 2,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 12,
      "name": "Waz",
      "position": "Goal",
      "appearances": 21,
      "goals": 0,
      "assists": 1,
      "goalInvolvements": 1,
      "motmVotes": 25,
      "motmWins": 3,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 1
    },
    {
      "id": 13,
      "name": "Brian",
      "position": "Midfield",
      "appearances": 11,
      "goals": 1,
      "assists": 2,
      "goalInvolvements": 3,
      "motmVotes": 4,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 14,
      "name": "Sam",
      "position": "Defence",
      "appearances": 9,
      "goals": 0,
      "assists": 2,
      "goalInvolvements": 2,
      "motmVotes": 15,
      "motmWins": 1,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 15,
      "name": "Ore",
      "position": "Defence",
      "appearances": 22,
      "goals": 1,
      "assists": 4,
      "goalInvolvements": 5,
      "motmVotes": 23,
      "motmWins": 1,
      "ownGoals": 1,
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 16,
      "name": "Waqaas",
      "position": "Defence",
      "appearances": 2,
      "goals": 0,
      "assists": 0,
      "goalInvolvements": 0,
      "motmVotes": 0,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 17,
      "name": "Ben J",
      "position": "Midfield",
      "appearances": 5,
      "goals": 1,
      "assists": 2,
      "goalInvolvements": 3,
      "motmVotes": 0,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 18,
      "name": "Beks",
      "position": "Striker",
      "appearances": 21,
      "goals": 8,
      "assists": 2,
      "goalInvolvements": 10,
      "motmVotes": 15,
      "motmWins": 1,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 19,
      "name": "James K",
      "position": "Midfield",
      "appearances": 13,
      "goals": 3,
      "assists": 1,
      "goalInvolvements": 4,
      "motmVotes": 4,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 20,
      "name": "Alex",
      "position": "Midfield",
      "appearances": 7,
      "goals": 2,
      "assists": 1,
      "goalInvolvements": 3,
      "motmVotes": 18,
      "motmWins": 3,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 21,
      "name": "James M",
      "position": "Midfield",
      "appearances": 13,
      "goals": 4,
      "assists": 2,
      "goalInvolvements": 6,
      "motmVotes": 13,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 1,
      "stabWounds": 0
    },
    {
      "id": 22,
      "name": "Gareth",
      "position": "Midfield",
      "appearances": 10,
      "goals": 2,
      "assists": 2,
      "goalInvolvements": 4,
      "motmVotes": 6,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 23,
      "name": "Tom N",
      "position": "Striker",
      "appearances": 1,
      "goals": 1,
      "assists": 0,
      "goalInvolvements": 1,
      "motmVotes": 0,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 24,
      "name": "Harry",
      "position": "Defence",
      "appearances": 4,
      "goals": 0,
      "assists": 0,
      "goalInvolvements": 0,
      "motmVotes": 5,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 25,
      "name": "Nando",
      "position": "Midfield",
      "appearances": 5,
      "goals": 0,
      "assists": 0,
      "goalInvolvements": 0,
      "motmVotes": 4,
      "motmWins": 1,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 26,
      "name": "Matt P",
      "position": "Defence",
      "appearances": 3,
      "goals": 0,
      "assists": 0,
      "goalInvolvements": 0,
      "motmVotes": 0,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 27,
      "name": "Ian",
      "position": "Midfield",
      "appearances": 20,
      "goals": 0,
      "assists": 6,
      "goalInvolvements": 6,
      "motmVotes": 22,
      "motmWins": 1,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 28,
      "name": "Matt S",
      "position": "Defence",
      "appearances": 13,
      "goals": 0,
      "assists": 0,
      "goalInvolvements": 0,
      "motmVotes": 17,
      "motmWins": 3,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    },
    {
      "id": 29,
      "name": "Jon",
      "position": "Midfield",
      "appearances": 0,
      "goals": 0,
      "assists": 0,
      "goalInvolvements": 0,
      "motmVotes": 0,
      "motmWins": 0,
      "ownGoals": 0,	
      "yellowCards": 0,
      "stabWounds": 0
    }
];